### ISSUE TITLE
WSAECONNRESET

### ISSUE THREAD

**Issue by coolboy4me** [Ekultek/BlueKeep#15]
i tried xp sp3, win7 64, win7 64 sp1, win2008 r2, all of them return me "unable to connect: (10054, 'WSAECONNRESET')", what can i do ?

**Comment by coolboy4me** [comment]
okay, the host can't be windows,  witch host to linux  and everything is ok

**Comment by patpatmok** [comment]
What linux platform you are using?

**Comment by coolboy4me** [comment]
> What linux platform you are using?

ubuntu 16.04
