### ISSUE TITLE
Windows 2008 R2/Windows 7 SP1 clean systems ECONRESET error

### ISSUE THREAD

**Issue by hittingbox** [Ekultek/BlueKeep#16]
Hello, was testing your code on clean installed and not updated systems (win 7 sp1, win 2008 r2) and got error (other crash pocs working on that system). How can i fix it? What problem it is?

[ + ] verifying RDP service on: 10.0.0.3
[ + ] successfully connected to RDP service on host: 10.0.0.3
[ + ] starting RDP connection on 1 targets

[ + ] sending Client MCS Connect Initial PDU request packet -->
[ + ] <-- received 0x70 bytes from host: 10.0.0.3
[ + ] sending Client MCS Domain Request PDU packet -->
[ + ] sending Client MCS Attach User PDU request packet -->
[ + ] <-- received 0xb bytes from host: 10.0.0.3
[ + ] sending MCS Channel Join Request PDU packets -->
[ + ] <-- received 0xf bytes from channel 1001 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1002 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1003 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1004 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1005 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1006 on host: 10.0.0.3
[ + ] <-- received 0xf bytes from channel 1007 on host: 10.0.0.3
[ + ] sending Client Security Exhcange PDU packets -->
[ + ] <-- received 0x22 bytes from host: 10.0.0.3
[ + ] sending Client Confirm Active PDU packet -->
[ + ] <-- received 0x1b9 bytes from host: 10.0.0.3
[ + ] sending Client Synchronization PDU packet -->
[ + ] sending Client Control Cooperate PDU packet -->
[ + ] sending Client Control Requesr PDU packet -->
[ + ] sending Client Persistent Key Length PDU packet -->
[ ! ] unable to connect: (104, 'ECONNRESET')

**Comment by coolboy4me** [comment]
i have the same problem with you and the answer is : be sure the host is linux,  and try a few more time. it's not stable

**Comment by hittingbox** [comment]
> i have the same problem with you and the answer is : be sure the host is linux, and try a few more time. it's not stable

It has been tested using the kali 2019.2

**Comment by pathsoft** [comment]
may be u need try it time and time again.

**Comment by drdoc** [comment]
it is now working, was trying about 30 hosts win 7 with different update status, and about 15 win 2008

**Comment by hittingbox** [comment]
it is now working, was trying about 30 hosts win 7 with different update status, and about 15 win 2008
