### ISSUE TITLE
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by leezp** [Ekultek/BlueKeep#21]
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

**Comment by reindo** [comment]
Changed from Network Level Authentication to the second option fixed this issue for me (System properties -> Remote). Seems like this isn't working if you have enforced NLA?

**Comment by Chapoly1305** [comment]
It worked！

![image](https://user-images.githubusercontent.com/25316415/63495364-46c5ab00-c4f2-11e9-8134-476135eba79f.png)
![image](https://user-images.githubusercontent.com/25316415/63495382-504f1300-c4f2-11e9-8d04-ec5e35e8977b.png)
