### ISSUE TITLE
Can you send me the payload, I just use it to joke with my friends.

### ISSUE THREAD

**Issue by hexhero** [Ekultek/BlueKeep#23]
yangb92@outlook.com.

thanksful.

**Comment by dksslq** [comment]
xdddd

**Comment by Ekultek** [comment]
Sent

**Comment by dksslq** [comment]
> Sent

really? I want too,thank you very much

**Comment by dksslq** [comment]
dksslq@gmail.com
thank you!

**Comment by hendr1k** [comment]
This seems unexpected, but while your at it, can you send it to me to? For educational purposes only offcoarse.

**Comment by dksslq** [comment]
I also want to use it to make a joke to my friends.

**Comment by zoujialan** [comment]
> 发送
Shelcode, do I want to be able to give it to me, too? 
E-mail address zoujialan@qq.com

**Comment by dksslq** [comment]
真实机翻

**Comment by zoujialan** [comment]
> 真实机翻

有前途

**Comment by temistocle33** [comment]
Ekultek can i get the payload? Just for educational purpose. 
Gregcarterize@gmail.com
Thanks

**Comment by zablah** [comment]
@Ekultek 
can I get the working payload Please?
zablah.zrata@gmail.com

**Comment by reg123reg** [comment]
@Ekultek
can I get the working payload Please? thank you very much
luxury0466@gmail.com

**Comment by 0xFF1E071F** [comment]
0xFF1E071F@protonmail.com
I need the payload for educational purposes only @Ekultek =) Thank you very much!
