### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sk3lk0** [Ekultek/BlueKeep#3]
root@root:~/$ python3 bluekeep_poc
Traceback (most recent call last):
  File "bluekeep_poc.py", line 6, in <module>
    from impacket.impacket.structure import Structure
ModuleNotFoundError: No module named 'impacket.impacket'

**Comment by NullArray** [comment]
Use the Python2.7 interpreter instead.

**Comment by sk3lk0** [comment]
need change
from impacket.impacket.structure import Structure
to
from impacket.structure import Structure

**Comment by n0chill** [comment]
> need from impacket.impacket.structure import Structure
> to
> from impacket.structure import Structure

How did you resolve this? I have tried installing and reinstall impacket and other dependencies.
