### ISSUE TITLE
how to attach the freed icachannel

### ISSUE THREAD

**Issue by lalkh** [Ekultek/BlueKeep#35]
after freed the ms_t120 channel,I tried to find one channel which I can send data to,however I cannot find one channel is binded before I login,I can send data to some channel but it cannot reach exallocatepoolwithtag because findchannel return 0,would you please give me some advice,thanks

**Comment by Ekultek** [comment]
https://github.com/Ekultek/BlueKeep/blob/master/research/%5BMS-RDPBCGR%5D.pdf
