### ISSUE TITLE
Double impacket

### ISSUE THREAD

**Issue by jdmastermy** [Ekultek/BlueKeep#4]
Need to remove double impacket due to the folder. or else it will keep asking for impacket module.

from impacket.impacket.structure import Structure

to

from impacket.structure import Structure

**Comment by binlmmhc** [comment]
just copy the structure.py to the bluekep_poc.py folder, and change "from impacket.impacket.structure import Structure" to "from structure import Structure" works fine.

**Comment by Ekultek** [comment]
Or just got clone it like you’re suppose to with the submodule

**Comment by Ekultek** [comment]
`git clone https://github.com/ekultek/bluekeep —recursive`

**Comment by Droid-MAX** [comment]
I fix it. Just use pip to install it.
