### ISSUE TITLE
ModuleNotFoundError: No module named 'impacket.impacket'

### ISSUE THREAD

**Issue by jianghoo** [Ekultek/BlueKeep#6]
ModuleNotFoundError: No module named 'impacket.impacket'

**Comment by SymmetriesSec** [comment]
In the folder:
"sudo pip install impacket".

Run: 
"python3 script.py".

**Comment by binlmmhc** [comment]
check issue 4.

**Comment by Droid-MAX** [comment]
There will be no such bugs anymore.

**Comment by Droid-MAX** [comment]
if python version is py2, just execute "python2 -m pip install -r requirements.txt", if py3, just replace "python2" to "python" and execute same command.
