### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by patpatmok** [Ekultek/BlueKeep#9]
Already using patched code
Target: Windows XP SP3
Attacker: Kali with Python 2.7

[ + ] verifying RDP service on: 172.12.0.136
[ + ] successfully connected to RDP service on host: 172.12.0.136
[ + ] starting RDP connection on 1 targets

[ ! ] unable to connect: (104, 'ECONNRESET')

**Comment by blockchainguard** [comment]
[ ! ] unable to connect: (104, 'Connection reset by peer')
